---
- name: PostgreSQL installation
  hosts: all
  become: yes
  become_user: root
  vars:
    - postgresql_users:
        - name: $USER #required; the rest are optional
          password: # defaults to not set
          login_host: # defaults to 'localhost'
          login_password: # defaults to not set
          login_user: # defaults to '{{ postgresql_user }}'
    - postgresql_databases:
        - name: $USER # required; the rest are optional
          login_host: # defaults to 'localhost'
          login_password: # defaults to not set
          login_user: # defaults to '{{ postgresql_user }}'
  tasks:
    - name: Installing postgresql 
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-client
    - name: Ensure PostgreSQL users are present.
      postgresql_user:
        name: "{{ item.name }}"
        password: "{{ item.password | default(omit) }}"
        login_host: "{{ item.login_host | default('localhost') }}"
        login_password: "{{ item.login_password | default(omit) }}"
        login_user: "{{ item.login_user | default(postgresql_user) }}"
        state: present
      with_items: "{{ postgresql_users }}"
      become: yes
      become_user: postgres
    - name: Ensure PostgreSQL databases are present.
      postgresql_db:
        name: "{{ item.name }}"
        login_host: "{{ item.login_host | default('localhost') }}"
        login_password: "{{ item.login_password | default(omit) }}"
        login_user: "{{ item.login_user | default(postgresql_user) }}"
        state: present
      with_items: "{{ postgresql_databases }}"
      become: true
      become_user: postgres
 