---
- name: Installing PostgreSQL
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql }}"
- name: "Install Python packages"
  pip:
    name: psycopg2-binary
    state: present  
- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "{{ pg_hba_config_path }}"
  register: postgres_data
- name: "Initialize PostgreSQL"
  shell:
    cmd: "service postgresql@12-main initdb"
  when: not postgres_data.stat.exists
- name: "Start and enable services"
  systemd:
    name: postgresql@12-main
    state: started
    enabled: yes
- name: "Create odoo database"
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: true
  become_user: "{{ db_root_user }}"
- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    role_attr_flags: CREATEDB,CREATEROLE,SUPERUSER
    password: "{{ db_password }}"
  become: true
  become_user: "{{ db_root_user }}"
- name: "Grant db user access to odoo db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: yes
    privs: all
  become: true
  become_user: "{{ db_root_user }}"
- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "{{ pg_hba_config_path }}"
    contype: local
    databases: "{{ db_user }}"
    method: md5
    users: "{{ db_user }}"
    create: true
  become: true
  become_user: "{{ db_root_user }}"
  notify: 
    - restart postgres
    - Reloading daemon and restarting odoo15
